# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 1 * * *"
    - cron: "30 13 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - run: |
          gh repo clone $GITHUB_REPOSITORY repo
          git -C repo config user.name "GitHub Actions"
          git -C repo config user.email "$USER@$HOST"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch SoC schedule
        run: |
          pip3 install bs4 lxml
          git -C repo checkout soc-sched
          wget --no-verbose -i list-soc-sched.txt
          ./commit-sched.sh
          git -C repo push https://oauth2:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Fetch CourseReg report
        run: |
          git -C repo checkout coursereg-report
          wget --no-verbose -i list-coursereg.txt
          ./commit-report.sh
          git -C repo push https://oauth2:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}
