name: CourseReg Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *" # 00:30 Asia/Singapore
    - cron: "30 4 * * *" # 12:30 Asia/Singapore

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh repo clone $GITHUB_REPOSITORY repo
          git -C repo config user.name "GitHub Actions"
          git -C repo config user.email "$USER@$HOST"
          git -C repo checkout coursereg-report
          ./update-report.sh
          git -C repo push https://oauth2:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}
