# This is a basic workflow to help you get started with Actions

name: SoC Course Schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 1 * * *"
    - cron: "30 13 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - run: |
          gh repo clone $GITHUB_REPOSITORY repo
          git -C repo checkout soc-sched
          pip3 install bs4
          ./update-sched.sh
          git -C repo push https://oauth2:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ github.token }}
